### ISSUE TITLE
Error: npm build / yarn build

### ISSUE THREAD

**Issue by blackgwe** [aurelia/experiment#14]
**I'm submitting a bug report**

* **Library Version:**
0.1.0

**Please tell us about your environment:**
* **Operating System:**
Linux (Arch)

* **Node Version:**
v9.10.1

* **NPM Version:**
5.6.0

**Current behavior:**
`npm build` throws an error:
```
compiler/index.ts → compiler/dist/aurelia-compiler.js...

[!] (rpt2 plugin) Error: /home/ai114/experiment/compiler/binding-language.ts(236,5): semantic error TS2454 Variable 'parts' is used before being assigned.
compiler/binding-language.ts

Error: /home/ai114/experiment/compiler/binding-language.ts(236,5): semantic error TS2454 Variable 'parts' is used before being assigned.

    at error (/home/ai114/experiment/node_modules/rollup/dist/rollup.js:168:15)
    at /home/ai114/experiment/node_modules/rollup/dist/rollup.js:19392:17
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
    at Function.Module.runMain (module.js:692:11)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:666:3
```

* **What is the motivation?**
I want to understand / debug the DI code.

**Comment by bigopon** [comment]
The last time I ran this it was working fine I think. While waiting you can head over the src folder and check the `.js` files to see temporary result of `.au` file compilation. Please note that it's about to change, as the runtime was changed a bit.
